dictionaries = []
words = [
    "discuit",
    "downvote",
    "jetstream",
    "signup",
    "unmute",
    "unsave",
    "upvote",
    "usermodel",
]
flag_words = []
ignore_paths = []
ignore_patterns = []
use_global = true
